<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="oak_woods_tileset" tilewidth="24" tileheight="24" tilecount="315" columns="21">
 <image source="../tlleset/oak_woods_tileset.png" width="504" height="360"/>
 <tile id="0" type="platform"/>
 <tile id="1" type="platform"/>
 <tile id="2" type="platform"/>
 <tile id="3" type="platform"/>
 <tile id="5" type="platform"/>
 <tile id="6" type="platform"/>
 <tile id="7" type="platform"/>
 <tile id="8" type="platform"/>
 <tile id="10" type="platform"/>
 <tile id="12" type="platform"/>
 <tile id="48" type="platform"/>
 <tile id="68" type="platform"/>
 <tile id="70" type="platform"/>
 <tile id="105" type="platform"/>
 <tile id="106" type="platform"/>
 <tile id="107" type="platform"/>
 <tile id="108" type="platform"/>
 <tile id="126" type="platform"/>
 <tile id="129" type="platform"/>
 <tile id="138" type="platform"/>
 <tile id="139" type="platform"/>
 <tile id="147" type="platform"/>
 <tile id="148" type="platform"/>
 <tile id="149" type="platform"/>
 <tile id="150" type="platform"/>
 <tile id="152" type="platform"/>
 <tile id="153" type="platform"/>
 <tile id="154" type="platform"/>
 <tile id="168" type="platform"/>
 <tile id="171" type="platform"/>
 <tile id="180" type="platform"/>
 <tile id="181" type="platform"/>
 <tile id="194" type="platform"/>
 <tile id="195" type="platform"/>
 <tile id="196" type="platform"/>
 <tile id="222" type="platform"/>
 <tile id="223" type="platform"/>
</tileset>
